# Generated by Django 2.2.7 on 2019-11-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensordata',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sensorvalues', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sensordata',
                'managed': False,
            },
        ),
    ]
