# Generated by Django 2.2.6 on 2019-11-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorValues', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('sensor_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_ID', models.IntegerField()),
                ('sensorValue', models.IntegerField()),
            ],
        ),
    ]
