# Generated by Django 2.2.7 on 2019-11-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sensor_1', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sensors',
                'managed': False,
            },
        ),
    ]
