# Generated by Django 2.2.7 on 2019-11-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='time',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
