# Generated by Django 2.2.7 on 2019-11-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191122_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='sensorValues',
            new_name='sensorValue',
        ),
    ]
