# Generated by Django 2.2.7 on 2019-11-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sensors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(db_column='sensor_ID')),
                ('sensorvalues', models.IntegerField()),
                ('timer', models.DateTimeField()),
            ],
            options={
                'db_table': 'datasensor',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Sensordata',
        ),
    ]
