# Generated by Django 2.2.6 on 2019-11-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191121_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='updated_at',
            new_name='created_at',
        ),
    ]
