# Generated by Django 2.2.6 on 2019-11-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191121_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
