# Generated by Django 2.2.6 on 2019-11-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191121_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
