# Generated by Django 2.2.6 on 2019-12-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_graph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graph',
        ),
    ]
