# Generated by Django 2.2.6 on 2019-11-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20191121_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorValues', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('sensor_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_ID', models.IntegerField()),
                ('sensorValue', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
