# Generated by Django 2.2.7 on 2019-11-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191114_1113'),
        ('dashboard', '0007_auto_20191121_1247'),
    ]

    operations = [
    ]
