# Generated by Django 2.2.6 on 2019-11-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.IntegerField(),
        ),
    ]
